name: 'Rancher Deploy'
description: 'Deploy to Rancher 1.6'
inputs:
  url:
    description: 'Rancher URL'
    required: true
  access_key:
    description: 'Rancher Access Key'
    required: true
  secret_key:
    description: 'Rancher Secret Key'
    required: true
  stack:
    description: 'Rancher Stack'
    required: true
  compose_file:
    description: 'Docker Compose File'
    required: false
    default: 'docker-compose.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RANCHER_URL: ${{ inputs.url }}
    RANCHER_ACCESS_KEY: ${{ inputs.access_key }}
    RANCHER_SECRET_KEY: ${{ inputs.secret_key }}
    RANCHER_STACK: ${{ inputs.stack }}
    COMPOSE_FILE: ${{ inputs.compose_file }}
