name: 'Rancher Deploy'
description: 'Deploy to Rancher 1.6'
inputs:
  url:
    description: 'Rancher URL'
    required: true
  access_key:
    description: 'Rancher Access Key'
    required: true
  secret_key:
    description: 'Rancher Secret Key'
    required: true
  stack:
    description: 'Rancher Stack'
    required: true
  compose_file:
    description: 'Docker Compose File'
    required: false
    default: 'docker-compose.yml'
  validate_compose_file:
    description: 'Validate Compose File'
    required: false
    default: "true"
  use_envsubst:
    description: 'Use envsubst for variable substitution'
    required: false
    default: "true"
  action:
    description: 'Actions to perform (deploy|confirm|rollback)'
    required: false
    default: "deploy,confirm"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RANCHER_URL: ${{ inputs.url }}
    RANCHER_ACCESS_KEY: ${{ inputs.access_key }}
    RANCHER_SECRET_KEY: ${{ inputs.secret_key }}
    RANCHER_STACK: ${{ inputs.stack }}
    RANCHER_ACTION: ${{ inputs.action }}
    COMPOSE_FILE: ${{ inputs.compose_file }}
    VALIDATE_COMPOSE_FILE: ${{ inputs.validate_compose_file }}
    USE_ENVSUBST: ${{ inputs.use_envsubst }}
